Delete brutil/tmp directory
reason. special characters in Portuguese language don't work well with software so it will cause necessary problems. Bollywood and Hollywood movies are English letters. So no special characters


```
😀💬 ~ git clone git@github.com:AbhimanyuAryan/movieClaude-dm.git
Cloning into 'movieClaude-dm'...
Enter passphrase for key '/c/Users/aryan/.ssh/id_ed25519':
remote: Enumerating objects: 4250, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 4250 (delta 0), reused 4 (delta 0), pack-reused 4245
Receiving objects: 100% (4250/4250), 102.57 MiB | 6.44 MiB/s, done.
Resolving deltas: 100% (1366/1366), done.
error: invalid path 'brutil/tmp/A Divisão: O Filme.json'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```